server:
  port: 8080  # Spring Boot 애플리케이션의 기본 HTTP 포트

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://3.36.67.192:3306/ssockssock?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mongle201
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
  mybatis:
    type-aliases-package: com.example.*
    mapper-locations: classpath:mappers/*.xml
    configuration:
      map-underscore-to-camel-case: true # DB 컬럼과 Java 필드 자동 매핑
jwt:
  header: Authorization
  secret: bG9uZ3JhbmRvbXNlY3JldGtleXNlY3VyaXR5Zm9yd2ViYXBwbG9uZ3JhbmRvbXNlY3JldGtleXNlY3VyaXR5Zm9yd2ViYXBwbG9uZ3JhbmRvbXNlY3JldGtleXNlY3VyaXR5Zm9yd2ViYXBw
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800

eureka:
  client:
    register-with-eureka: true  # 유레카 서버에 등록
    fetch-registry: true  # 다른 서비스 정보 가져오기
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka Server 주소